name: CI

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        version: latest
        virtualenvs-create: true
        virtualenvs-in-project: true
    
    - name: Cache Poetry dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/pypoetry
          .venv
        key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
        restore-keys: |
          ${{ runner.os }}-poetry-
    
    - name: Set up Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: ui/package-lock.json
    
    - name: Install Python dependencies
      run: |
        cd backend
        poetry install --no-interaction --no-root
    
    - name: Install Node.js dependencies
      run: npm ci --prefix ui
    
    - name: Run Python tests
      run: |
        cd backend
        poetry run pytest -v
    
    - name: Run frontend lint
      run: npm run lint --prefix ui
    
    - name: Run TypeScript check
      run: npm run typecheck --prefix ui
    
    - name: Build frontend
      run: npm run build --prefix ui